### ISSUE TITLE
getOutputPath outputs source file path, not output path

### ISSUE THREAD

**Issue by budparr** [static-dev/spike-util#22]
The `_path` [variable](https://github.com/static-dev/spike-collections/blob/master/lib/index.js#L109) in the Jekyll Template index.sgr [view template](https://github.com/static-dev/spike-tpl-jekyll/blob/master/root/views/index.sgr#L8) outputs the source file path with a `.sgr` extension.

To replicate, run a fresh install of spike using the Jekyll template and compile the site. Note the home page listing of blog posts, outputs URL's, for example:
```
posts/9-26-2016-hello-world.sgr
```

I would expect this output:
```
posts/9-26-2016-hello-world.html or, optionally posts/9-26-2016-hello-world/
```

I was hoping to submit this as a nice starting pull request, but haven't been able to figure it out. 😦

**Comment by jescalan** [comment]
Oh yeah good catch here, let me take a look at this and try to get it fixed

**Comment by jescalan** [comment]
Ok so the easiest fix would be manually substituting whatever extension is on there for `.html` within the collections plugin, similar to how it is [done in the core](https://github.com/static-dev/spike-core/blob/master/lib/plugin.js#L72). This is probably what should be done immediately as a fix.

However, I'm thinking the best fix here long-term might be to make the `getOutputPath` method a bit more powerful and have it detect and swap extensions where necessary. This would be breaking, however, and would require adjustment in a number of plugins that use this method.

I think the best way to find the extension would be to run a search for the file path on `compiler.options.spike.files.process`, which is [set here](https://github.com/static-dev/spike-core/blob/master/lib/plugin.js#L186), and is an object that includes the output extension. Shouldn't be too difficult really, the main blocker is just that the change is breaking and would require a decent number of changes to other places that implement spike-util.

**Comment by budparr** [comment]
Interesting. I had tried to replace it manually (knowing it wouldn't be a permanent fix), but I wasn't doing it right. I'll see how far I can take this. Thank you.

One question though. Some people would want to specify (in app.js) to output extensions, and (most) others would not. Does that come into play here?

**Comment by jescalan** [comment]
Yeah so the extensions listed in `compiler.options.spike.files.process` will include any type of custom extensions, or the default extension -- that's the one source of truth 😁

**Comment by budparr** [comment]
closing here and will follow up in the template or spike-collections.
