### ISSUE TITLE
Can getOutputPath include root path "/"

### ISSUE THREAD

**Issue by budparr** [static-dev/spike-util#23]
Spike Collections specifies the `_path` variable as [relative](https://github.com/static-dev/spike-collections/blob/master/lib/index.js#L105), but I think it should do so with a forward slash for its root:

Currently outputs:
```
posts/9-26-2016-hello-world.sgr
```
But I would expect the output to be:
```
/posts/9-26-2016-hello-world.sgr
```
So _path would work from any directory.

Again, apologies for the issue instead of pull request, but it's not for not trying, and I'm happy to do the leg work with a pointer or two.

**Comment by jescalan** [comment]
Hmm, ok I can get down with that. I think you should be able to just concat `/` before it and that would do the trick!

**Comment by budparr** [comment]
You can. I was thinking this would be more standard, though perhaps not.

**Comment by jescalan** [comment]
Right, I mean you could just concat the `/` in the source 😁

**Comment by budparr** [comment]
Cool. I'll do that.
